name = "FunSQL"
uuid = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
authors = ["Kirill Simonov <xi@resolvent.net>", "Clark C. Evans <cce@clarkevans.com>"]
version = "0.11.1"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DBInterface = "2.5"
LRUCache = "1.3"
OrderedCollections = "1.4"
PrettyPrinting = "0.3.2, 0.4"
Tables = "1.6"
julia = "1.6"
